### ISSUE TITLE
Build on jessie (i386) with no Qt already installed

### ISSUE THREAD

**Issue by jimbolaya** [doctormord/OpenBuudai#2]
There were a large number of packages that needed to be installed on my system that had no other Qt apps on it.

`# apt-get install qt4-qmake`

`# apt-get install libqt4-dev`, which installs:
```
libmysqlclient18 libqt4-declarative libqt4-designer libqt4-dev libqt4-dev-bin libqt4-help libqt4-network
libqt4-opengl libqt4-opengl-dev libqt4-qt3support libqt4-script libqt4-scripttools libqt4-sql libqt4-sql-mysql
libqt4-svg libqt4-test libqt4-xmlpatterns libqtwebkit-dev libqtwebkit4 mysql-common qt4-linguist-tools

```
Then the libfftw3-3 development:
`# apt-get install libfftw3-dev` which installs:
`libfftw3-bin libfftw3-dev libfftw3-long3 libfftw3-quad3`

Finally (for me), the libusb-1.0 libraries:
`# apt-get install libusb-1.0-dev` which installs:
`libusb-1.0-0-dev libusb-1.0-doc`

```
# qmake
# make
```

I just browsed through OpenHantek.pro and saw mentioned there the changes for Linux. Make sure you change the appropriate lines.

**Comment by doctormord** [comment]
Thanks for this.
